"""Inactive V3-1B Company Kernel schema and immutable records.

Importing this package performs no migration and exposes no company action,
execution, scheduling, projection, acceptance, or reconciliation gateway.
"""

from .models import (
    ACCEPTANCE_ID_DOMAIN,
    ATTEMPT_ID_DOMAIN,
    COMPANY_ID_DOMAIN,
    COMPANY_KERNEL_MODEL_VERSION,
    COMPANY_KERNEL_SCHEMA_COMPONENT,
    COMPANY_KERNEL_SCHEMA_VERSION,
    MISSION_ID_DOMAIN,
    OUTCOME_ID_DOMAIN,
    PLAN_REVISION_ID_DOMAIN,
    RECONCILIATION_ID_DOMAIN,
    WORK_PACKAGE_ID_DOMAIN,
    AcceptanceCommit,
    Company,
    KernelReconciliationReceipt,
    Mission,
    PlanRevision,
    WorkPackage,
    WorkPackageAttempt,
    canonical_hash,
    canonical_json,
    derive_identity,
    normalize_outcome_identity,
    normalize_work_package_contract,
    outcome_id_for,
    route_request_hash,
    work_package_contract_hash,
)
from .schema import (
    COMPANY_KERNEL_INDEX_NAMES,
    COMPANY_KERNEL_MIGRATIONS,
    COMPANY_KERNEL_TABLE_NAMES,
    COMPANY_KERNEL_TRIGGER_NAMES,
)
from .store import CompanyKernelStore

__all__ = [
    "ACCEPTANCE_ID_DOMAIN",
    "ATTEMPT_ID_DOMAIN",
    "COMPANY_ID_DOMAIN",
    "COMPANY_KERNEL_INDEX_NAMES",
    "COMPANY_KERNEL_MIGRATIONS",
    "COMPANY_KERNEL_MODEL_VERSION",
    "COMPANY_KERNEL_SCHEMA_COMPONENT",
    "COMPANY_KERNEL_SCHEMA_VERSION",
    "COMPANY_KERNEL_TABLE_NAMES",
    "COMPANY_KERNEL_TRIGGER_NAMES",
    "MISSION_ID_DOMAIN",
    "OUTCOME_ID_DOMAIN",
    "PLAN_REVISION_ID_DOMAIN",
    "RECONCILIATION_ID_DOMAIN",
    "WORK_PACKAGE_ID_DOMAIN",
    "AcceptanceCommit",
    "Company",
    "CompanyKernelStore",
    "KernelReconciliationReceipt",
    "Mission",
    "PlanRevision",
    "WorkPackage",
    "WorkPackageAttempt",
    "canonical_hash",
    "canonical_json",
    "derive_identity",
    "normalize_outcome_identity",
    "normalize_work_package_contract",
    "outcome_id_for",
    "route_request_hash",
    "work_package_contract_hash",
]
